# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Main_GUI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Text Retrieval")
        Dialog.setFixedSize(694, 577)
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(570, 10, 111, 31))
        self.search_btn.setObjectName("search_btn")
        self.query_input = QtWidgets.QLineEdit(Dialog)
        self.query_input.setGeometry(QtCore.QRect(10, 10, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.query_input.setFont(font)
        self.query_input.setObjectName("query_input")
        self.query_input.setPlaceholderText("Enter your query")
        self.result_view = QtWidgets.QListWidget(Dialog)
        self.result_view.setGeometry(QtCore.QRect(10, 50, 671, 511))
        self.result_view.setObjectName("result_view")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Text Retrieval", "Text Retrieval"))
        self.search_btn.setText(_translate("Text Retrieval", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Main_GUI()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
